CREATE DATABASE GESPRO
GO
USE GESPRO
GO
CREATE TABLE RESPONSABLES
(
	IDRESPONSABLE		INTEGER IDENTITY PRIMARY KEY,
	NOMBRE				VARCHAR(300)
)
GO
CREATE TABLE TAREAS
(
	IDTAREA			INTEGER IDENTITY PRIMARY KEY,
	PRIORIDAD		INTEGER,
	FECHAREGISTRO	DATETIME,
	FECHALIMITE		DATETIME,
	IDRESPONSABLE	INTEGER,
	FOREIGN KEY (IDRESPONSABLE) REFERENCES RESPONSABLES(IDRESPONSABLE)
)

